name: jzero-ci

on:
  push:
    branches:
  pull_request:

jobs:
  golangci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install Jzero and Grum
        run: |
          go install github.com/jzero-io/jzero@main
          jzero check
          go install github.com/jaronnie/grum@latest

      - name: Test Usage
        run: |
          jzero new simpleapi --branch api
          cd simpleapi
          jzero gen
          jzero gen sdk
          jzero gen swagger
          go mod tidy && go run main.go version